### ISSUE TITLE
noticed some big undocumented changes

### ISSUE THREAD

**Issue by DanielRuf** [symfony/skeleton#19]
It seems like we have to use index as method name instead of indexAction in Symfony 4?

Also `make` fails because it can not be used on/ is not available on Windows but Symfony tries to execute it (running Git Bash on Windows which uses Mingw64).

~And in the cache directory I found some `de_` next to the `dev` directory (and saw a message about Kerne_) and the namespace is `App` instead of `AppBundle`.~ (probably forgot one cache command)

**Comment by Pierstoval** [comment]
> It seems like we have to use index as method name instead of indexAction in Symfony 4?

This is not a SF4 issue, this is about the routing system, allowing us not to add the suffix `Action` to controller methods when using annotations or controller as services.

> Also `make` fails because it can not be used on/ is not available on Windows but Symfony tries to execute it (running Git Bash on Windows which uses Mingw64).

For the makefile, I tried my best to find the possible issues with the Win32 version of GNU make, but couldn't find what's going on. Make is available on Windows, but it is not exactly the same as 100% unix one. And Windows doesn't use unix commands like `rm -rf` for `clear-cache` for example. So I think the makefile will never be compatible with windows, and we'll have to either refactor it manually, or consider not using it on Windows at all. Or use Bash On Ubuntu On Windows, or Cygwin, or Mingw, or any unix emulator, and it'll work like a charm.

> And in the cache directory I found some `de_` next to the `dev` directory (and saw a message about Kerne_) and the namespace is `App` instead of `AppBundle`.

About `de_`, I think it's because the `cache:clear` command warms up the cache and therefore create other directories for this, this is something that should disappear when SF4 comes up, because the `--no-warmup` will be implicit in SF4 when clearing the cache.

About the namespace, it has changed because there is no default bundle in the SF4 / Flex structure, which is quite obvious when creating a project with Flex & Symfony.
The fact that the namespace is `App` instead of an empty one is because having a configured namespace in `psr-4` directives in `composer.json` gives a boost to performances contrary to the use of `"": "src/"` or other empty `psr-4` directives.
Any nice IDE with PHP & Composer features will automatically understand the namespaces.

These are not "big undocumented" changes. The "no-warmup" deprecation has been [announced in the blog](https://symfony.com/blog/new-in-symfony-3-3-deprecated-cache-clear-with-warmup), Flex structure is not completely documented because it's still in alpha, therefore possibly subject to changes, and the action suffix is just a native Symfony feature since years ago. And for the makefile, I don't know why there would be documentation. Just type "makefile documentation" on any search engine and you'll end up with thousands of pages, because makefiles have been existing for years.

**Comment by DanielRuf** [comment]
What about shelljs for the make commands? https://github.com/shelljs/shelljs

> This is not a SF4 issue, this is about the routing system, allowing us not to add the suffix Action to controller methods when using annotations or controller as services.
But it works just without `Action` or does it just work with `Action` when we switch to annotations? Because it did not work this way.

> About the namespace, it has changed because there is no default bundle in the SF4 / Flex structure, which is quite obvious when creating a project with Flex & Symfony.
> The fact that the namespace is App instead of an empty one is because having a configured namespace in psr-4 directives in composer.json gives a boost to performances contrary to the use of "": "src/" or other empty psr-4 directives.
> Any nice IDE with PHP & Composer features will automatically understand the namespaces.

Right, I miss this bit of information in the SF4 blogposts and master docs ;-)

I just meant that the `de_` dir which was left was a bit weird. We already found both commands and used them but this directory was still there in one case.

**Comment by Pierstoval** [comment]
> What about shelljs for the make commands? https://github.com/shelljs/shelljs

I'd say "no way", adding a node.js layer just for commands sounds like an overhead to me. Make is standard in all unix-based systems, and Windows can handle unix-based systems too via Cygwin, Mingw or WSL.

> But it works just without `Action` or does it just work with `Action` when we switch to annotations? Because it did not work this way.

Routing annotations & routing with controller as services accept the full method name. Only the `Bundle:Controller:method` need `method` to be named `methodAction()` in the controller class.

**Comment by DanielRuf** [comment]
> I'd say "no way", adding a node.js layer just for commands sounds like an overhead to me. Make is standard in all unix-based systems, and Windows can handle unix-based systems too via Cygwin, Mingw or WSL.

You are right but I guess we also have a solution for composer.
Mingw is used by the Git Bash as I stated in the initial comment but the make command is not available there.

> Only the Bundle:Controller:method need method to be named methodAction() in the controller class.

Isn't this the case in the default config when I comment the first few lines in?

> It's just a behavior from the cache:clear command when --no-warmup is not specified.

Ok, so it was probably some remnant of a previous execution where this was forgotten?

Hm, so this line https://github.com/symfony/recipes/blob/master/symfony/routing/3.3/config/routes.yaml#L3 has nothing to do with `indexAction` and wants `index`? Just to be clear, this only worked with `index` and not `indexAction`.

Thanks for answering my questions so far.

**Comment by DanielRuf** [comment]
At least it is not a great solution with the make file. I' research further and hope to find some solutions that we could use instead of `make`.

https://packagist.org/packages/tivie/command
https://github.com/MrRio/shellwrap

**Comment by Pierstoval** [comment]
> Hm, so this line https://github.com/symfony/recipes/blob/master/symfony/routing/3.3/config/routes.yaml#L3 has nothing to do with (...)

It's using the services syntax, because the controller is automatically registered as service in default Flex project, and the service name is the FQCN, so this syntax is the service one, and the method name should then be `index()`.

>At least it is not a great solution with the make file. I' research further and hope to find some solutions that we could use instead of `make.` 
> https://packagist.org/packages/tivie/commandhttps://github.com/MrRio/shellwrap

These packages add more coupling to the project.

I'd like more something that would be a single composer script, like `composer make ...` for example, but same, it's not the best option either because it also adds coupling to another script.

There are only two solutions:

1. Keep the Makefile as-is, and forget about native Windows compliancy (too much work)
2. Spend hours/days/weeks/months/years maintaining a makefile that would be compatible with Windows

I'd go for 1.

**Comment by DanielRuf** [comment]
Thanks for the clarification. Makes much sense as it is now provided as a service.

You are right regarding Windows support, not easy. I had hopes to have better support on Windows 10.

**Comment by Pierstoval** [comment]
@DanielRuf The fact that we have WSL is a form of better support 😉

**Comment by DanielRuf** [comment]
For sure = )
