### ISSUE TITLE
optimize-autoloader flag

### ISSUE THREAD

**Issue by nehalist** [symfony/skeleton#202]
Just curious about why #180 has been merged when the [flag docs](https://getcomposer.org/doc/articles/autoloader-optimization.md#autoloader-optimization) states:

> Note: You should not enable any of these optimizations in development as they all will cause various problems when adding/removing classes. The performance gains are not worth the trouble in a development setting.

Any reason to use it nonetheless?

**Comment by lyrixx** [comment]
I'm not sure the doc is still relevant, it works well in practice.

**Comment by MatTheCat** [comment]
FWIW I noticed this flag because when renaming a class using PhpStorm it also modified the classmap, so the new class was located in the old file :grimacing: 

EDIT: after some investigation PhpStorm did this because I un-excluded vendor directories by misunderstanding the point (cf. https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000112599-Prevent-PHPStorm-from-automatically-exclude-some-folders).
