### ISSUE TITLE
Why is "symfony/thanks" added to composer.json?

### ISSUE THREAD

**Issue by tarlepp** [symfony/skeleton#50]
Lots of discussion about this on slack.

And if this is a skeleton why it has package that doesn't have really meaning ?

**Comment by nicolas-grekas** [comment]
Just to invalidate a misconception I saw on Slack: the thanks plugin doesn't do ANYTHING unless YOU call "composer thanks".

The meaning of this package is to allow thankful users to discover the command easily, and then use it when they want. Of course, it's also to promote sending good vibes to OSS authors.

**Comment by moon-deer** [comment]
First of all, of course, it is very good initiative to "say thank you" in some way for all those developers who share their work for a community. 

But I thought the meaning of Symfony is to set highly professional standards. Including "thanks" doesn't feels really professional. 

Why should it be a "**surprise**" to see during installation process that there's some package installing that has **nothing** to do with the framework that you choose for your project?
Then you need to spend your time to discover what is this, why it's even included in the skeleton, what it's actually doing and then remove it, because you already supporting those developers with your way to "thanks" them.

**Comment by nicolas-grekas** [comment]
Saying "thanks" is very professional. But I would also say it is one of the most missing interaction in enterprise world...

There are no single way to say thanks, and they are no exclusive to each others.

OSS is never cold code: it's built by actual human beings. See the talk from Compsoer's Jordi and many other OSS leaders to know how much negative vibes they get instead of good ones. I think we need to actively find ways to counter balance this. And every stones count to achieve this.

Last: nobody forces anyone doing anything. So if you don't like what some authors pushes forward (like this plugin), just don't use their code, or fork their code, that's fine.

**Comment by Pierstoval** [comment]
Yes, let's fork `symfony/skeleton` and tell the world to use `whatever/symfony-other-skeleton-without-thanks-because-it-is-not-professional`. I'm sure everyone will totally agree that it's legit and professionnal.

I'm totally fan of the idea of including `symfony/thanks`: this leads to a better view of the open-source community when developers start a new project.

For years, I met a lot of companies that said things like "Symfony is too big/bloated/overkill/complex/for the elite/selfish" and other dump and false words, sometimes much harder and violent words.

By helping developers saying "thanks", it's like a worldwide educational project: everyone saying "thanks" will probably unconsciously realize that the open-source community is full of human beings that deserve to be thanked for their free work, because OSS is free, and built in the free time of every contributor.

Making the IT community grow worldwide to help all companies make more money, doesn't this deserve at least a single command-line instruction that you can use anytime?

**Comment by moon-deer** [comment]
@nicolas-grekas "nobody forces anyone doing anything"
1. This statement opposite to the fact that something like "thanks" package included in the skeleton.
2. This doesn't solve any problem, because people who don't care, for them this is just bull**it. And people who cares already doing everything they can to support those cool devs.

So, again. There's no sense in this.

**Comment by jwage** [comment]
The thanks package is a great idea. Low cost, low effort and big impact to our ecosystem that has a high net win. This issue and the comments on it are being overly pedantic for no good reason. This issue does more harm to the project and it’s maintainers than anything.

**Comment by Pierstoval** [comment]
You're right @jwage, and I would even go further: this issue could be close right now without warning.

As nicolas-grekas said above, we could just search for a few of seldaek's blog posts about people yelling at him about something they don't like to see that people who don't accept to thank OSS maintainers for their hard work do not even deserve a publicly opened issue and discussion.

And I would go even more further by saying this:

`symfony/thanks` should even be mandatory (and even integrated to Composer), because when you use free projects to make money, it's mandatory to be kind with them. Period.

**Comment by dunglas** [comment]
And it's a dev dep... It will not even reach your production server.

**Comment by tarlepp** [comment]
@nicolas-grekas Thanks for clear answer about this. 

Seems like this still divides community - which is really shame. And of course everyone can has different opinion about this. But now that question has a answer it's pointless to continue this discussion within this issue, so closing this.

And to make clear, personally I haven't anything against that thanks package, it's really usefull tool for some people.

**Comment by nicolas-grekas** [comment]
I'm locking as some comments were deleted, so the remaining ones are a bit out of context now.
